// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  DefaultFirebaseOptions._(); // Private constructor to prevent instantiation

  /// Returns appropriate FirebaseOptions for the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        throw _unsupportedPlatformError('windows');
      case TargetPlatform.linux:
        throw _unsupportedPlatformError('linux');
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Helper method to throw UnsupportedError
  static UnsupportedError _unsupportedPlatformError(String platform) {
    return UnsupportedError(
      'DefaultFirebaseOptions have not been configured for $platform - '
          'you can reconfigure this by running the FlutterFire CLI again.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCc9adRZ4wxxM2TTNVRhK63Q22ELbCVbd8",
      authDomain: "flutter-sp-95355.firebaseapp.com",
      projectId: "flutter-sp-95355",
      storageBucket: "flutter-sp-95355.appspot.com",
      messagingSenderId: "10712319956",
      appId: "1:10712319956:web:b892e07f307b39fc0a7841"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB58BszEz7ahwU_OJ9XbUcxiVP1LgJVJmY',
    appId: '1:10712319956:android:8ff5fdfdab34280c0a7841',
    messagingSenderId: '10712319956',
    projectId: 'flutter-sp-95355',
    storageBucket: 'flutter-sp-95355.appspot.com',
  );
}